spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/jss?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true